### ISSUE TITLE
Error when running the built app in mac

### ISSUE THREAD

**Issue by DavidWells** [react-photonkit/epp#2]
Hello. Awesome demo here!

Everything works great for the development flow.

But after running `npm run build-osx` the app throws this error when the epp.app is run.

![image](https://cloud.githubusercontent.com/assets/532272/12990575/f92286b8-d0bf-11e5-8ba1-623ef2863bf8.png)

`Uncaught Exception:
TypeError: win.loadURL is not a function
    at createMainWindow (/Users/davidwells/Scratch/epp/dist/Epp-darwin-x64/Epp.app/Contents/Resources/app.asar/index.js:40:7)
    at EventEmitter.<anonymous> (/Users/davidwells/Scratch/epp/dist/Epp-darwin-x64/Epp.app/Contents/Resources/app.asar/index.js:73:15)
    at emitOne (events.js:82:20)
    at EventEmitter.emit (events.js:169:7)`

Any ideas on how to fix?

Thanks!

**Comment by importre** [comment]
Hi @DavidWells.

It works now. Please see d4c9cf1665459ee1083ab7ef379f54ab3ac7eae1

**Comment by DavidWells** [comment]
aha! Thanks =)

Great example app!
