### ISSUE TITLE
SyntaxError: Use of const in strict mode

### ISSUE THREAD

**Issue by alexflint** [react-photonkit/epp#5]
With a clean checkout of master:

```
$ npm start

> epp@0.0.0 start /Users/alex/Code/scratch/epp
> node starter.js --2nd

/Users/alex/Code/scratch/epp/starter.js:5
const net = require('net');
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

**Comment by importre** [comment]
I think it will be resolved if you use latest version of nodejs. please check the version.
