### ISSUE TITLE
Start and Build Error

### ISSUE THREAD

**Issue by omidnavy** [react-photonkit/epp#7]
Hey everyone
I was trying to run this , but it returns errors , btw i'm a big noob with react , I dont know how to fix it , these are the errors:

`
0 info it worked if it ends with ok

1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@3.10.8
3 info using node@v6.9.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle epp@0.0.0~prestart: epp@0.0.0
6 silly lifecycle epp@0.0.0~prestart: no script for prestart, continuing
7 info lifecycle epp@0.0.0~start: epp@0.0.0
8 verbose lifecycle epp@0.0.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle epp@0.0.0~start: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\Users\PFG - Navy\Desktop\epp-master\node_modules\.bin;c:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\ProgramData\Oracle\Java\javapath;C:\xampp\php;C:\Windows\System32;C:\Program Files (x86)\Skype\Phone\;C:\xampp\php5.2.9;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\ProgramData\chocolatey\bin;C:\tools\python2;C:\Program Files\Git\cmd;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\HashiCorp\Vagrant\bin;C:\Users\PFG - Navy\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\nodejs\;C:\Program Files (x86)\SSH Communications Security\SSH Secure Shell;C:\Program Files (x86)\Microsoft VS Code\bin;C:\Users\PFG - Navy\AppData\Local\Microsoft\WindowsApps;C:\Users\PFG - Navy\AppData\Roaming\npm
10 verbose lifecycle epp@0.0.0~start: CWD: C:\Users\PFG - Navy\Desktop\epp-master
11 silly lifecycle epp@0.0.0~start: Args: [ '/d /s /c', 'node starter.js --2nd' ]
12 silly lifecycle epp@0.0.0~start: Returned: code: 1  signal: null
13 info lifecycle epp@0.0.0~start: Failed to exec start script
14 verbose stack Error: epp@0.0.0 start: `node starter.js --2nd`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid epp@0.0.0
16 verbose cwd C:\Users\PFG - Navy\Desktop\epp-master
17 error Windows_NT 10.0.14393
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
19 error node v6.9.1
20 error npm  v3.10.8
21 error code ELIFECYCLE
22 error epp@0.0.0 start: `node starter.js --2nd`
22 error Exit status 1
23 error Failed at the epp@0.0.0 start script 'node starter.js --2nd'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the epp package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node starter.js --2nd
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs epp
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls epp
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
`

**Comment by CarbonChili** [comment]
Yes I can report I am having the same issue trying to install or build on win 8.1 x64. I have fixed this partially by ensuring I have the windows SDK for 8.1 installed and the CL.exe is pointing to the right place. Now it builds ok (with a few warnings) but it does not run.

**Comment by gracegrimwood** [comment]
This appears to be the same issue as #8.
