### ISSUE TITLE
starter.js throws 'spawn webpack-dev-server ENOENT' error on Windows 10

### ISSUE THREAD

**Issue by yolandavdvegt** [react-photonkit/epp#8]
starter.js throws throws an error while spawning the webpack-dev-server on Windows 10.

```bash
$ npm start

> epp@0.0.0 start C:\Users\Yolanda\Projects\epp
> node starter.js --2nd

events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn webpack-dev-server ENOENT
    at exports._errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v7.1.0
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
npm ERR! epp@0.0.0 start: `node starter.js --2nd`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the epp@0.0.0 start script 'node starter.js --2nd'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the epp package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node starter.js --2nd
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs epp
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls epp
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Yolanda\Projects\epp\npm-debug.log
```

The solution that worked for me is to spawn webpack-dev-server by [win-spawn](https://www.npmjs.com/package/win-spawn)

Fix in this pull request: #9

**Comment by gracegrimwood** [comment]
Having the same issue, commit c770a8957770f744d570bcbbb6c7e375aff15460 did not fix.

Powershell output:
```
PS D:\Desktop\SWEN302\epp-master> npm start

> epp@0.0.0 start D:\Desktop\SWEN302\epp-master
> node starter.js --2nd

sleep: using busy loop fallback
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: spawn webpack-dev-server ENOENT
    at _errnoException (util.js:1041:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:192:19)
    at onErrorNT (internal/child_process.js:374:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! epp@0.0.0 start: `node starter.js --2nd`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the epp@0.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\grace\AppData\Roaming\npm-cache\_logs\2017-09-15T01_42_56_323Z-debug.log
```

Logfile output:
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start',
1 verbose cli   '-dd' ]
2 info using npm@5.3.0
3 info using node@v8.4.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle epp@0.0.0~prestart: epp@0.0.0
6 info lifecycle epp@0.0.0~start: epp@0.0.0
7 verbose lifecycle epp@0.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle epp@0.0.0~start: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;D:\Desktop\SWEN302\epp-master\node_modules\.bin;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;c:\Program Files\Intel\WiFi\bin\;c:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files (x86)\GtkSharp\2.12\bin;C:\Program Files (x86)\Skype\Phone\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\dotnet\;C:\Program Files\Anaconda3;C:\Program Files\Anaconda3\Scripts;C:\Program Files\Anaconda3\Library\bin;C:\Users\grace\AppData\Local\Programs\Python\Python36\Scripts\;C:\Users\grace\AppData\Local\Programs\Python\Python36\;C:\Program Files\Git\cmd;C:\Program Files\Gauge\bin;C:\Program Files (x86)\Java\jdk1.8.0_131\bin;C:\Program Files (x86)\Android\android-sdk\platform-tools;C:\Program Files\nodejs\;D:\node_modules\.bin\;D:\trid_w32\;D:\cURL\curl-7.55.1;C:\Users\grace\AppData\Local\Microsoft\WindowsApps;C:\Program Files (x86)\FAHClient;C:\Users\grace\AppData\Local\atom\bin;C:\Users\grace\AppData\Local\GitHubDesktop\bin;C:\Users\grace\AppData\Roaming\npm
9 verbose lifecycle epp@0.0.0~start: CWD: D:\Desktop\SWEN302\epp-master
10 silly lifecycle epp@0.0.0~start: Args: [ '/d /s /c', 'node starter.js --2nd' ]
11 silly lifecycle epp@0.0.0~start: Returned: code: 1  signal: null
12 info lifecycle epp@0.0.0~start: Failed to exec start script
13 verbose stack Error: epp@0.0.0 start: `node starter.js --2nd`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:289:16)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at EventEmitter.emit (events.js:213:7)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at ChildProcess.emit (events.js:213:7)
13 verbose stack     at maybeClose (internal/child_process.js:927:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
14 verbose pkgid epp@0.0.0
15 verbose cwd D:\Desktop\SWEN302\epp-master
16 verbose Windows_NT 10.0.15063
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start" "-dd"
18 verbose node v8.4.0
19 verbose npm  v5.3.0
20 error code ELIFECYCLE
21 error errno 1
22 error epp@0.0.0 start: `node starter.js --2nd`
22 error Exit status 1
23 error Failed at the epp@0.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```
Edit: Should probably mention that I am also using Win10, specifically version 1703 build 15063.608
